### ISSUE TITLE
is_inside_path error

### ISSUE THREAD

**Issue by Incubatio** [nfvs/vim-perforce#10]
trying to edit a file with let g:perforce_open_on_change=1
```
Error detected while processing function perforce#P4CallEditWithPrompt[6]..<SNR>33_IsPathInP4:
line    1:
E461: Illegal variable name: a:is_inside_path
```
I replaced "a:is_inside_path" by "is_inside_path" and it seem to work now.

VIM - Vi IMproved 8.1
macOs Version

**Comment by nfvs** [comment]
I can't really reproduce this error, but `a:` is nevertheless the wrong prefix there. I've fixed it in the last commit, let me know if it's still happening.
