### ISSUE TITLE
Should prompting be optional and disabled by default ?

### ISSUE THREAD

**Issue by Incubatio** [nfvs/vim-perforce#11]
I'm not sure prompting is relevant in the case of P4revert.
As you voluntarily type P4revert, you are actively reverting your file and you still have vim undo to "revert your revert" as long as you don't close vim.

Also I'm just starting to work with perforce, but it sounds a bit tedious to either type P4edit for each file, or to be prompted when editing (when  g:perforce_open_on_change=1), or to have w! and then be prompted.

If you're in noAllWrite mode, as the file is readOnly, you already need to force w (w!), which again is something the user types for this sole purpose.

And if you're in allWrite mode, and you save without P4edit you gonna to have use a p4 status to track file that have been modified but not added, which gonna do a full scan (slow and painfull).

If this prompting could be somehow usefull (like people working on project with readonly files outside of perforce version control ?), maybe it could be optional, like g:perforce_prompting=0)

Could fill me in on your design choices, and correct me if misunderstood smth ?

**Comment by nfvs** [comment]
vim-perforce follows the P4V convention: displays a prompt if the file being reverted contains changes, no prompt otherwise.

You can already disable prompting with `g:perforce_prompt_on_open = 0`.

https://github.com/nfvs/vim-perforce#gperforce_prompt_on_open-default-1
