### ISSUE TITLE
"Error detected while processing function perforce#P4CallEdit[3]. <SNR>33_err:"

### ISSUE THREAD

**Issue by Dev0Null** [nfvs/vim-perforce#4]
I just installed this plugin via `vundle`, and there seems to be an issue whenever I attempt to open a file in my test Perforce staging area. When I attempt to write to a file, I encounter a warning that the file is read-only, and am prompted to `Open the file in Perforce? Y/N`. When I select `Y`, the dialog goes away, and presents an error message (shown below). After forcefully writing to the file, Perforce does not recognize the change, suggesting that the `p4 edit` command issued by the plugin did not succeed.

![p4_plugin_vim](https://cloud.githubusercontent.com/assets/8325672/24810668/f8d5ead4-1b77-11e7-8086-a61d07152e18.png)

Is this an issue with the plugin itself, or some incompatible setting in `.vimrc`? 

Thank you!

**Comment by Dev0Null** [comment]
Closing issue. Turned out to be issues with permissions associated with the local working copy.

**Comment by wKavey** [comment]
Digging this up from the grave, but any chance you can share your solution? I am hitting the same issue (same error) when answering [Y]es to the "File is read only. Attempt to open in Perforce?" prompt.

**Comment by nfvs** [comment]
What are the permissions for the file you're trying to open?

**Comment by wKavey** [comment]
`-r-xr-xr-x 1 my_user my_group 8.1K Jan  8 10:56 data_files.py`

**Comment by nfvs** [comment]
Right, no write permissions. `chmod +w data_files` should fix it.

**Comment by nfvs** [comment]
Uh that made no sense, of course you're absolutely right.

I can't reproduce that, what OS/P4 version are you using?

**Comment by wKavey** [comment]
```
» p4 -V
...
Version of OpenSSL Libraries: OpenSSL 1.0.2n  7 Dec 2017
Rev. P4/LINUX26X86_64/2018.1/1637071 (2018/03/23).
```
Running SUSE Linux SP1

I'm in no way familiar with vimscript, Is there any way I can extract a better error message? 'Error detected while processing' isnt too helpful, wish I could pinpoint more.

**Comment by nfvs** [comment]
Can you update to the latest version and add `let g:perforce_debug=1` to your `.vimrc`? Then try `:P4edit` in the file you're having trouble with, followed by `:messages`, and print the output (feel free to strip anything you don't want to share).

**Comment by nfvs** [comment]
No prob. I just updated the plugin with more meaningful output on error, so if you update to the latest version you should be able to debug it easily.
