### ISSUE TITLE
Paths with spaces

### ISSUE THREAD

**Issue by coder79** [nfvs/vim-perforce#6]
Operations on paths with spaces (via Windows) do not properly escape the path.  For example, P4edit will produce a shell command like:

p4 edit path\foo bar\baz.cpp

Resulting in a "not under client's root" for the first and second half of the path.  Perhaps the expanded paths should be wrapped in shellescape()?

**Comment by nfvs** [comment]
Good find @coder79, can you confirm it's fixed in the latest version?

**Comment by coder79** [comment]
Yes, it's working for me now.  I tested relative and absolute paths using P4edit, P4revert, and via autocmd BufWritePre.  Thanks for the fast fix!
