### ISSUE TITLE
"E730: using List as a String" when calling P4edit 

### ISSUE THREAD

**Issue by stowelly** [nfvs/vim-perforce#7]
Recently updated all my plugins, and now for some reason this happens when i try to edit a file (the end result is that the file is not checked out, but this is the full error)

thanks

Error detected while processing function perforce#P4CallEdit..<SNR>59_P4ShellCurrentBuffer..<SNR>59_P4Shell:
line    2:
E730: using List as a String
vim-perforce: File open for edit.

**Comment by nfvs** [comment]
I can't reproduce this. How do you try to edit the file, by running `P4Edit` on the current buffer? By answering `y` in the prompt when you try to save a read-only file?

**Comment by stowelly** [comment]
just by typing :P4edit but it also does it when answering y 

(my vim version incase thats of any importance VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:42:52)(

**Comment by nfvs** [comment]
Windows, Mac or Linux?

**Comment by stowelly** [comment]
Linux (ubuntu 14.04)

**Comment by nfvs** [comment]
I can't reproduce this. What happens if you run `P4revert`, or `P4info`?

**Comment by stowelly** [comment]
P4info outputs the correct info

P4revert however:
Error detected while processing function perforce#P4CallRevert..<SNR>55_P4ShellCurrentBuffer..<SNR>55_P4Shell:
line    2:
E730: using List as a String
E730: using List as a String
vim-perforce: File reverted.


is there any logging or anything i can enable or add to help with this?

**Comment by stowelly** [comment]
just calling :!p4 edit % works fine also

**Comment by nfvs** [comment]
I've submitted a fix in a different branch, but there's no way to install it with Vundle. You have to go to the plugin dir (`~/.vim/bundle/vim-perforce`) and try to checkout that branch: `git checkout listfix`

**Comment by stowelly** [comment]
the only branches I can see are development and master, neither of which has the file "listfix" (maybe im missing something here?)

**Comment by nfvs** [comment]
`listfix` is the branch, not the file; you may need to do a `git pull` to get all branches first.

**Comment by stowelly** [comment]
mike@mike-work-linux:~/.vim/bundle/vim-perforce|master
⇒  git checkout listfix
error: pathspec 'listfix' did not match any file(s) known to git.
mike@mike-work-linux:~/.vim/bundle/vim-perforce|master
⇒  git pull
Already up-to-date.
mike@mike-work-linux:~/.vim/bundle/vim-perforce|master
⇒  git branch -a       
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/development
  remotes/origin/master
mike@mike-work-linux:~/.vim/bundle/vim-perforce|master
⇒

**Comment by nfvs** [comment]
Sorry, my bad, it seems Vundle changes the git remote url when you specify a local dir. Checkout `development` and try that instead.

**Comment by stowelly** [comment]
Thanks. I switched to development and pulled the latest, and still the same issue :s

**Comment by nfvs** [comment]
Can you paste the exact error?

**Comment by nfvs** [comment]
Also the first few lines of P4info:
```
User name:
Client name:
Client host:
Client root:
Current directory:
```

**Comment by stowelly** [comment]
Error detected while processing function perforce#P4CallEdit..<SNR>59_P4ShellCur
rentBuffer..<SNR>59_P4Shell:
line    2:
E730: using List as a String
Error detected while processing function perforce#P4CallEdit..<SNR>59_err:
line    1:
vim-perforce: Unable to open file for edit.    


P4info (removed some company information)

User name: Michael.Stowell
Client name: Michael.Stowell_mike-work-linux_*****_task15940_******_1_5_95
59
Client host: mike-work-linux
Client root: /home/mike/tw/Michael.Stowell_linux_stream
Client stream: //streams/*****_dev_features
Current directory: /home/mike/tw/Michael.Stowell_linux_stream/online_service/******

**Comment by nfvs** [comment]
> 59_P4Shell:
> line 2:

P4Shell now only has 1 line, so that's probably not using the correct branch.

**Comment by stowelly** [comment]
function! s:P4Shell(cmd, ...)
  return call('system', [g:vim_perforce_executable . ' ' . a:cmd] + a:000)
endfunction

is my local version

**Comment by stowelly** [comment]
wait a sec.
im using vim-plug i think that may use a different location! ill double check

**Comment by stowelly** [comment]
Yes for whatever reason vim-plug fetches from git then copies it to its own folder! the development branch has this fixed!

thank you!

**Comment by nfvs** [comment]
Great, will merge into `master`.
